version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=programme
      - POSTGRES_PASSWORD=programme
      - POSTGRES_DB=programme
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  task_manager:
    build:
      context: .
      dockerfile: Dockerfile.task-manager
    restart: always
    environment:
      - POSTGRES_USER=programme
      - POSTGRES_PASSWORD=programme
      - POSTGRES_DB=programme
    links:
      - postgres

  mobile_gateway:
    build:
      context: .
      dockerfile: Dockerfile.mobile-gateway
    restart: always
    links:
      - task_manager
      - weather_api

  weather_api:
    build:
      context: .
      dockerfile: Dockerfile.weather-api
    restart: always
    env_file:
      - ../openweathermap.key
