// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shared/model/mobile/mobile.proto

package mobile // import "github.com/rhino1998/programme/backend/lib/model/mobile"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import schedule "github.com/rhino1998/programme/backend/lib/model/schedule"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MobileGatewayClient is the client API for MobileGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MobileGatewayClient interface {
	AddTask(ctx context.Context, in *schedule.NewTaskRequest, opts ...grpc.CallOption) (*schedule.Boolean, error)
}

type mobileGatewayClient struct {
	cc *grpc.ClientConn
}

func NewMobileGatewayClient(cc *grpc.ClientConn) MobileGatewayClient {
	return &mobileGatewayClient{cc}
}

func (c *mobileGatewayClient) AddTask(ctx context.Context, in *schedule.NewTaskRequest, opts ...grpc.CallOption) (*schedule.Boolean, error) {
	out := new(schedule.Boolean)
	err := c.cc.Invoke(ctx, "/shared.model.mobile.MobileGateway/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobileGatewayServer is the server API for MobileGateway service.
type MobileGatewayServer interface {
	AddTask(context.Context, *schedule.NewTaskRequest) (*schedule.Boolean, error)
}

func RegisterMobileGatewayServer(s *grpc.Server, srv MobileGatewayServer) {
	s.RegisterService(&_MobileGateway_serviceDesc, srv)
}

func _MobileGateway_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(schedule.NewTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileGatewayServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shared.model.mobile.MobileGateway/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileGatewayServer).AddTask(ctx, req.(*schedule.NewTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MobileGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shared.model.mobile.MobileGateway",
	HandlerType: (*MobileGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _MobileGateway_AddTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/model/mobile/mobile.proto",
}

func init() {
	proto.RegisterFile("shared/model/mobile/mobile.proto", fileDescriptor_mobile_1c5b22dc3aa5f0a7)
}

var fileDescriptor_mobile_1c5b22dc3aa5f0a7 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xce, 0x48, 0x2c,
	0x4a, 0x4d, 0xd1, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0xcf, 0xcd, 0x4f, 0xca, 0xcc, 0x49, 0x85,
	0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xc2, 0x10, 0x15, 0x7a, 0x60, 0x15, 0x7a, 0x10,
	0x29, 0x29, 0x15, 0x14, 0x6d, 0xc5, 0xc9, 0x19, 0xa9, 0x29, 0xa5, 0x39, 0xa9, 0x70, 0x06, 0x44,
	0xab, 0x51, 0x22, 0x17, 0xaf, 0x2f, 0x58, 0xbd, 0x7b, 0x62, 0x49, 0x6a, 0x79, 0x62, 0xa5, 0x50,
	0x00, 0x17, 0xbb, 0x63, 0x4a, 0x4a, 0x48, 0x62, 0x71, 0xb6, 0x90, 0xaa, 0x1e, 0x8a, 0xb9, 0x70,
	0x9d, 0x7e, 0xa9, 0xe5, 0x20, 0xf9, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x29, 0x39, 0x1c,
	0xca, 0x9c, 0xf2, 0xf3, 0x73, 0x52, 0x13, 0xf3, 0x9c, 0x72, 0x2f, 0x3c, 0x94, 0x63, 0xb8, 0xf1,
	0x50, 0x8e, 0xe1, 0xc3, 0x43, 0x39, 0xc6, 0x86, 0x47, 0x72, 0x8c, 0x2b, 0x1e, 0xc9, 0x31, 0x9e,
	0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x2f, 0x1e, 0xc9, 0x31,
	0x7c, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb,
	0x31, 0x44, 0x99, 0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0x65,
	0x64, 0xe6, 0xe5, 0x1b, 0x5a, 0x5a, 0x5a, 0xe8, 0x17, 0x14, 0xe5, 0xa7, 0x17, 0x25, 0xe6, 0xe6,
	0xa6, 0xea, 0x27, 0x25, 0x26, 0x67, 0xa7, 0xe6, 0xa5, 0xe8, 0xe7, 0x64, 0x26, 0xa1, 0x84, 0x4c,
	0x12, 0x1b, 0xd8, 0x63, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x8a, 0x25, 0x61, 0x37,
	0x01, 0x00, 0x00,
}
