// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather.proto

package forcast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Geo location of city
type Coord struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Lattitude            float64  `protobuf:"fixed64,2,opt,name=lattitude,proto3" json:"lattitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{0}
}
func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Coord) GetLattitude() float64 {
	if m != nil {
		return m.Lattitude
	}
	return 0
}

type Sys struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Sunrise              uint64   `protobuf:"varint,2,opt,name=sunrise,proto3" json:"sunrise,omitempty"`
	Sunset               uint64   `protobuf:"varint,3,opt,name=sunset,proto3" json:"sunset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sys) Reset()         { *m = Sys{} }
func (m *Sys) String() string { return proto.CompactTextString(m) }
func (*Sys) ProtoMessage()    {}
func (*Sys) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{1}
}
func (m *Sys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sys.Unmarshal(m, b)
}
func (m *Sys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sys.Marshal(b, m, deterministic)
}
func (m *Sys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sys.Merge(m, src)
}
func (m *Sys) XXX_Size() int {
	return xxx_messageInfo_Sys.Size(m)
}
func (m *Sys) XXX_DiscardUnknown() {
	xxx_messageInfo_Sys.DiscardUnknown(m)
}

var xxx_messageInfo_Sys proto.InternalMessageInfo

func (m *Sys) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Sys) GetSunrise() uint64 {
	if m != nil {
		return m.Sunrise
	}
	return 0
}

func (m *Sys) GetSunset() uint64 {
	if m != nil {
		return m.Sunset
	}
	return 0
}

type Main struct {
	Temperature          float64  `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TempMin              float64  `protobuf:"fixed64,2,opt,name=temp_min,json=tempMin,proto3" json:"temp_min,omitempty"`
	TempMax              float64  `protobuf:"fixed64,3,opt,name=temp_max,json=tempMax,proto3" json:"temp_max,omitempty"`
	Pressure             float64  `protobuf:"fixed64,4,opt,name=pressure,proto3" json:"pressure,omitempty"`
	SeaLevel             float64  `protobuf:"fixed64,5,opt,name=sea_level,json=seaLevel,proto3" json:"sea_level,omitempty"`
	GrndLevel            float64  `protobuf:"fixed64,6,opt,name=grnd_level,json=grndLevel,proto3" json:"grnd_level,omitempty"`
	Humidity             int64    `protobuf:"varint,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
	TempKf               int64    `protobuf:"varint,8,opt,name=temp_kf,json=tempKf,proto3" json:"temp_kf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Main) Reset()         { *m = Main{} }
func (m *Main) String() string { return proto.CompactTextString(m) }
func (*Main) ProtoMessage()    {}
func (*Main) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{2}
}
func (m *Main) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Main.Unmarshal(m, b)
}
func (m *Main) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Main.Marshal(b, m, deterministic)
}
func (m *Main) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Main.Merge(m, src)
}
func (m *Main) XXX_Size() int {
	return xxx_messageInfo_Main.Size(m)
}
func (m *Main) XXX_DiscardUnknown() {
	xxx_messageInfo_Main.DiscardUnknown(m)
}

var xxx_messageInfo_Main proto.InternalMessageInfo

func (m *Main) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Main) GetTempMin() float64 {
	if m != nil {
		return m.TempMin
	}
	return 0
}

func (m *Main) GetTempMax() float64 {
	if m != nil {
		return m.TempMax
	}
	return 0
}

func (m *Main) GetPressure() float64 {
	if m != nil {
		return m.Pressure
	}
	return 0
}

func (m *Main) GetSeaLevel() float64 {
	if m != nil {
		return m.SeaLevel
	}
	return 0
}

func (m *Main) GetGrndLevel() float64 {
	if m != nil {
		return m.GrndLevel
	}
	return 0
}

func (m *Main) GetHumidity() int64 {
	if m != nil {
		return m.Humidity
	}
	return 0
}

func (m *Main) GetTempKf() int64 {
	if m != nil {
		return m.TempKf
	}
	return 0
}

// Mainly use id from this, can
type Weather struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Main                 string   `protobuf:"bytes,2,opt,name=main,proto3" json:"main,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather) Reset()         { *m = Weather{} }
func (m *Weather) String() string { return proto.CompactTextString(m) }
func (*Weather) ProtoMessage()    {}
func (*Weather) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{3}
}
func (m *Weather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather.Unmarshal(m, b)
}
func (m *Weather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather.Marshal(b, m, deterministic)
}
func (m *Weather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather.Merge(m, src)
}
func (m *Weather) XXX_Size() int {
	return xxx_messageInfo_Weather.Size(m)
}
func (m *Weather) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather.DiscardUnknown(m)
}

var xxx_messageInfo_Weather proto.InternalMessageInfo

func (m *Weather) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Weather) GetMain() string {
	if m != nil {
		return m.Main
	}
	return ""
}

func (m *Weather) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Wind struct {
	Speed                float64  `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Deg                  float64  `protobuf:"fixed64,2,opt,name=deg,proto3" json:"deg,omitempty"`
	Gust                 float64  `protobuf:"fixed64,3,opt,name=gust,proto3" json:"gust,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wind) Reset()         { *m = Wind{} }
func (m *Wind) String() string { return proto.CompactTextString(m) }
func (*Wind) ProtoMessage()    {}
func (*Wind) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{4}
}
func (m *Wind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wind.Unmarshal(m, b)
}
func (m *Wind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wind.Marshal(b, m, deterministic)
}
func (m *Wind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wind.Merge(m, src)
}
func (m *Wind) XXX_Size() int {
	return xxx_messageInfo_Wind.Size(m)
}
func (m *Wind) XXX_DiscardUnknown() {
	xxx_messageInfo_Wind.DiscardUnknown(m)
}

var xxx_messageInfo_Wind proto.InternalMessageInfo

func (m *Wind) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Wind) GetDeg() float64 {
	if m != nil {
		return m.Deg
	}
	return 0
}

func (m *Wind) GetGust() float64 {
	if m != nil {
		return m.Gust
	}
	return 0
}

type Rain struct {
	ThreeHours           int64    `protobuf:"varint,1,opt,name=three_hours,json=threeHours,proto3" json:"three_hours,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rain) Reset()         { *m = Rain{} }
func (m *Rain) String() string { return proto.CompactTextString(m) }
func (*Rain) ProtoMessage()    {}
func (*Rain) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{5}
}
func (m *Rain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rain.Unmarshal(m, b)
}
func (m *Rain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rain.Marshal(b, m, deterministic)
}
func (m *Rain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rain.Merge(m, src)
}
func (m *Rain) XXX_Size() int {
	return xxx_messageInfo_Rain.Size(m)
}
func (m *Rain) XXX_DiscardUnknown() {
	xxx_messageInfo_Rain.DiscardUnknown(m)
}

var xxx_messageInfo_Rain proto.InternalMessageInfo

func (m *Rain) GetThreeHours() int64 {
	if m != nil {
		return m.ThreeHours
	}
	return 0
}

type Snow struct {
	ThreeHours           int64    `protobuf:"varint,1,opt,name=three_hours,json=threeHours,proto3" json:"three_hours,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snow) Reset()         { *m = Snow{} }
func (m *Snow) String() string { return proto.CompactTextString(m) }
func (*Snow) ProtoMessage()    {}
func (*Snow) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{6}
}
func (m *Snow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snow.Unmarshal(m, b)
}
func (m *Snow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snow.Marshal(b, m, deterministic)
}
func (m *Snow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snow.Merge(m, src)
}
func (m *Snow) XXX_Size() int {
	return xxx_messageInfo_Snow.Size(m)
}
func (m *Snow) XXX_DiscardUnknown() {
	xxx_messageInfo_Snow.DiscardUnknown(m)
}

var xxx_messageInfo_Snow proto.InternalMessageInfo

func (m *Snow) GetThreeHours() int64 {
	if m != nil {
		return m.ThreeHours
	}
	return 0
}

type Clouds struct {
	All                  int64    `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clouds) Reset()         { *m = Clouds{} }
func (m *Clouds) String() string { return proto.CompactTextString(m) }
func (*Clouds) ProtoMessage()    {}
func (*Clouds) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{7}
}
func (m *Clouds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clouds.Unmarshal(m, b)
}
func (m *Clouds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clouds.Marshal(b, m, deterministic)
}
func (m *Clouds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clouds.Merge(m, src)
}
func (m *Clouds) XXX_Size() int {
	return xxx_messageInfo_Clouds.Size(m)
}
func (m *Clouds) XXX_DiscardUnknown() {
	xxx_messageInfo_Clouds.DiscardUnknown(m)
}

var xxx_messageInfo_Clouds proto.InternalMessageInfo

func (m *Clouds) GetAll() int64 {
	if m != nil {
		return m.All
	}
	return 0
}

type List struct {
	Dt                   int64      `protobuf:"varint,1,opt,name=dt,proto3" json:"dt,omitempty"`
	Main                 *Main      `protobuf:"bytes,2,opt,name=main,proto3" json:"main,omitempty"`
	Weather              []*Weather `protobuf:"bytes,3,rep,name=weather,proto3" json:"weather,omitempty"`
	Clouds               *Clouds    `protobuf:"bytes,4,opt,name=clouds,proto3" json:"clouds,omitempty"`
	Wind                 *Wind      `protobuf:"bytes,5,opt,name=wind,proto3" json:"wind,omitempty"`
	Rain                 *Rain      `protobuf:"bytes,6,opt,name=rain,proto3" json:"rain,omitempty"`
	Sys                  *Sys       `protobuf:"bytes,7,opt,name=sys,proto3" json:"sys,omitempty"`
	DtTxt                string     `protobuf:"bytes,8,opt,name=dt_txt,json=dtTxt,proto3" json:"dt_txt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{8}
}
func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetDt() int64 {
	if m != nil {
		return m.Dt
	}
	return 0
}

func (m *List) GetMain() *Main {
	if m != nil {
		return m.Main
	}
	return nil
}

func (m *List) GetWeather() []*Weather {
	if m != nil {
		return m.Weather
	}
	return nil
}

func (m *List) GetClouds() *Clouds {
	if m != nil {
		return m.Clouds
	}
	return nil
}

func (m *List) GetWind() *Wind {
	if m != nil {
		return m.Wind
	}
	return nil
}

func (m *List) GetRain() *Rain {
	if m != nil {
		return m.Rain
	}
	return nil
}

func (m *List) GetSys() *Sys {
	if m != nil {
		return m.Sys
	}
	return nil
}

func (m *List) GetDtTxt() string {
	if m != nil {
		return m.DtTxt
	}
	return ""
}

type City struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coord                *Coord   `protobuf:"bytes,3,opt,name=coord,proto3" json:"coord,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{9}
}
func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *City) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *City) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type Forecast struct {
	Cod                  int64    `protobuf:"varint,1,opt,name=cod,proto3" json:"cod,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cnt                  int64    `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	List                 []*List  `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	City                 *City    `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Forecast) Reset()         { *m = Forecast{} }
func (m *Forecast) String() string { return proto.CompactTextString(m) }
func (*Forecast) ProtoMessage()    {}
func (*Forecast) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{10}
}
func (m *Forecast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Forecast.Unmarshal(m, b)
}
func (m *Forecast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Forecast.Marshal(b, m, deterministic)
}
func (m *Forecast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Forecast.Merge(m, src)
}
func (m *Forecast) XXX_Size() int {
	return xxx_messageInfo_Forecast.Size(m)
}
func (m *Forecast) XXX_DiscardUnknown() {
	xxx_messageInfo_Forecast.DiscardUnknown(m)
}

var xxx_messageInfo_Forecast proto.InternalMessageInfo

func (m *Forecast) GetCod() int64 {
	if m != nil {
		return m.Cod
	}
	return 0
}

func (m *Forecast) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Forecast) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

func (m *Forecast) GetList() []*List {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *Forecast) GetCity() *City {
	if m != nil {
		return m.City
	}
	return nil
}

func init() {
	proto.RegisterType((*Coord)(nil), "forcast.Coord")
	proto.RegisterType((*Sys)(nil), "forcast.Sys")
	proto.RegisterType((*Main)(nil), "forcast.Main")
	proto.RegisterType((*Weather)(nil), "forcast.Weather")
	proto.RegisterType((*Wind)(nil), "forcast.Wind")
	proto.RegisterType((*Rain)(nil), "forcast.Rain")
	proto.RegisterType((*Snow)(nil), "forcast.Snow")
	proto.RegisterType((*Clouds)(nil), "forcast.Clouds")
	proto.RegisterType((*List)(nil), "forcast.List")
	proto.RegisterType((*City)(nil), "forcast.City")
	proto.RegisterType((*Forecast)(nil), "forcast.Forecast")
}

func init() { proto.RegisterFile("weather.proto", fileDescriptor_231dcd72b885f4be) }

var fileDescriptor_231dcd72b885f4be = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0x13, 0x3b,
	0x10, 0x56, 0xb2, 0x9b, 0x4d, 0x32, 0x7b, 0xda, 0x53, 0x59, 0xe7, 0xc0, 0x52, 0xfe, 0xc2, 0x0a,
	0xa9, 0x15, 0x17, 0xbd, 0x08, 0x6f, 0x40, 0x24, 0x84, 0x44, 0x2b, 0x84, 0x8b, 0xd4, 0xcb, 0xc8,
	0xac, 0xdd, 0xc4, 0xb0, 0xb1, 0x23, 0xdb, 0x4b, 0x93, 0x67, 0x40, 0xe2, 0x45, 0x79, 0x09, 0x34,
	0xb3, 0xde, 0x24, 0x54, 0x48, 0xdc, 0xcd, 0x37, 0xdf, 0xb7, 0x9e, 0xf1, 0x37, 0xe3, 0x85, 0xa3,
	0x3b, 0x25, 0xc2, 0x52, 0xb9, 0x8b, 0xb5, 0xb3, 0xc1, 0xb2, 0xe1, 0xad, 0x75, 0x95, 0xf0, 0xa1,
	0x9c, 0xc1, 0x60, 0x66, 0xad, 0x93, 0xec, 0x09, 0x8c, 0x6b, 0x6b, 0x16, 0x3a, 0x34, 0x52, 0x15,
	0xbd, 0x49, 0xef, 0xbc, 0xc7, 0xf7, 0x09, 0x62, 0x45, 0x08, 0x2d, 0xdb, 0x8f, 0x6c, 0x97, 0x28,
	0x3f, 0x42, 0x72, 0xbd, 0xf5, 0xac, 0x80, 0x61, 0x65, 0x1b, 0x13, 0xdc, 0x96, 0x0e, 0x18, 0xf3,
	0x0e, 0x22, 0xe3, 0x1b, 0xe3, 0xb4, 0x6f, 0x3f, 0x4e, 0x79, 0x07, 0xd9, 0x03, 0xc8, 0x7c, 0x63,
	0xbc, 0x0a, 0x45, 0x42, 0x44, 0x44, 0xe5, 0xcf, 0x1e, 0xa4, 0x57, 0x42, 0x1b, 0x36, 0x81, 0x3c,
	0xa8, 0xd5, 0x5a, 0x39, 0x11, 0x1a, 0xd7, 0x75, 0x76, 0x98, 0x62, 0x8f, 0x60, 0x84, 0x70, 0xbe,
	0xd2, 0x26, 0xb6, 0x36, 0x44, 0x7c, 0xa5, 0xcd, 0x9e, 0x12, 0x1b, 0x3a, 0xbf, 0xa3, 0xc4, 0x86,
	0x9d, 0xc2, 0x68, 0xed, 0x94, 0xf7, 0x78, 0x68, 0x4a, 0xd4, 0x0e, 0xb3, 0xc7, 0x30, 0xf6, 0x4a,
	0xcc, 0x6b, 0xf5, 0x4d, 0xd5, 0xc5, 0xa0, 0x25, 0xbd, 0x12, 0x97, 0x88, 0xd9, 0x53, 0x80, 0x85,
	0x33, 0x32, 0xb2, 0x59, 0xeb, 0x05, 0x66, 0x5a, 0xfa, 0x14, 0x46, 0xcb, 0x66, 0xa5, 0xa5, 0x0e,
	0xdb, 0x62, 0x38, 0xe9, 0x9d, 0x27, 0x7c, 0x87, 0xd9, 0x43, 0xa0, 0xf2, 0xf3, 0xaf, 0xb7, 0xc5,
	0x88, 0xa8, 0x0c, 0xe1, 0xfb, 0xdb, 0xf2, 0x03, 0x0c, 0x6f, 0xda, 0xf9, 0xb0, 0x63, 0xe8, 0x6b,
	0x49, 0xd7, 0x4c, 0x78, 0x5f, 0x4b, 0xc6, 0x20, 0x5d, 0x89, 0x78, 0xb3, 0x31, 0xa7, 0x18, 0x3d,
	0x91, 0xca, 0x57, 0x4e, 0xaf, 0x83, 0xb6, 0x86, 0x6e, 0x36, 0xe6, 0x87, 0xa9, 0xf2, 0x0d, 0xa4,
	0x37, 0xda, 0x48, 0xf6, 0x1f, 0x0c, 0xfc, 0x5a, 0x29, 0x19, 0x7d, 0x6b, 0x01, 0x3b, 0x81, 0x44,
	0xaa, 0x45, 0x34, 0x0b, 0x43, 0xac, 0xb2, 0x68, 0x7c, 0x88, 0x26, 0x51, 0x5c, 0x9e, 0x41, 0xca,
	0xb1, 0xda, 0x73, 0xc8, 0xc3, 0xd2, 0x29, 0x35, 0x5f, 0xda, 0xc6, 0xf9, 0xd8, 0x1a, 0x50, 0xea,
	0x1d, 0x66, 0x50, 0x78, 0x6d, 0xec, 0xdd, 0xdf, 0x85, 0xa7, 0x90, 0xcd, 0x6a, 0xdb, 0x48, 0x8f,
	0x1d, 0x88, 0xba, 0x8e, 0x12, 0x0c, 0xcb, 0xef, 0x7d, 0x48, 0x2f, 0xb5, 0x0f, 0x68, 0x80, 0x0c,
	0x9d, 0x01, 0x32, 0xb0, 0x17, 0x07, 0x06, 0xe4, 0xd3, 0xa3, 0x8b, 0xb8, 0xb9, 0x17, 0xb8, 0x1d,
	0xd1, 0x8f, 0x57, 0x30, 0x8c, 0xeb, 0x5d, 0x24, 0x93, 0xe4, 0x3c, 0x9f, 0x9e, 0xec, 0x54, 0xd1,
	0x56, 0xde, 0x09, 0xd8, 0x19, 0x64, 0x15, 0xf5, 0x40, 0x53, 0xcf, 0xa7, 0xff, 0xee, 0xa4, 0x6d,
	0x6b, 0x3c, 0xd2, 0x58, 0xf7, 0x4e, 0x1b, 0x49, 0xf3, 0x3f, 0xac, 0x8b, 0xbe, 0x72, 0xa2, 0x50,
	0xe2, 0xb0, 0xb5, 0xec, 0x9e, 0x84, 0x53, 0x6b, 0x48, 0xb1, 0x67, 0x90, 0xf8, 0xad, 0xa7, 0x4d,
	0xc8, 0xa7, 0xff, 0xec, 0x14, 0xd7, 0x5b, 0xcf, 0x91, 0x60, 0xff, 0x43, 0x26, 0xc3, 0x3c, 0x6c,
	0x02, 0x6d, 0xc4, 0x98, 0x0f, 0x64, 0xf8, 0xb4, 0x09, 0xe5, 0x17, 0x48, 0x67, 0xb8, 0x31, 0x7f,
	0xd8, 0x06, 0x23, 0x56, 0xaa, 0xdb, 0x06, 0x8c, 0xd9, 0x4b, 0x18, 0x54, 0xf8, 0x84, 0x69, 0x78,
	0xf9, 0xf4, 0x78, 0x7f, 0x21, 0xcc, 0xf2, 0x96, 0x3c, 0x7c, 0x9c, 0xe9, 0x6f, 0x8f, 0xb3, 0xfc,
	0xd1, 0x83, 0xd1, 0x5b, 0xeb, 0x14, 0x7e, 0x83, 0x83, 0xa9, 0x6c, 0x57, 0x11, 0x43, 0xfc, 0x70,
	0xa5, 0xbc, 0x17, 0x8b, 0xae, 0x6a, 0x07, 0x49, 0x6b, 0xda, 0x9d, 0x41, 0xad, 0xa1, 0x59, 0xd5,
	0xda, 0x87, 0x22, 0xa5, 0x29, 0xec, 0x0d, 0xc1, 0xc1, 0x72, 0xa2, 0x50, 0x52, 0xe1, 0xdb, 0xb8,
	0x6f, 0x2b, 0x5e, 0x97, 0x13, 0xf5, 0x39, 0xa3, 0x7f, 0xd4, 0xeb, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x12, 0x52, 0xe9, 0xda, 0xb4, 0x04, 0x00, 0x00,
}
